/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    AppNavBar: typeof import('./components/AppNavBar.vue')['default']
    CustomNavBar: typeof import('./components/CustomNavBar.vue')['default']
    CustomTabBar: typeof import('./components/CustomTabBar.vue')['default']
  }
}
