/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/production/automation" |
  "/pages/production/index" |
  "/pages/production/monitor" |
  "/pages/production/report" |
  "/pages/production/sales" |
  "/pages/production/video" |
  "/pages/profile/about" |
  "/pages/profile/favorites" |
  "/pages/profile/feedback" |
  "/pages/profile/index" |
  "/pages/profile/messages" |
  "/pages/profile/settings" |
  "/pages/profile/tasks" |
  "/pages/safety/contacts" |
  "/pages/safety/environmental" |
  "/pages/safety/hazard" |
  "/pages/safety/index" |
  "/pages/safety/monitor" |
  "/pages/safety/risk" |
  "/pages/safety/warning-detail" |
  "/pages/safety/warning";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/safety/index" | "/pages/production/index" | "/pages/knowledge/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
